eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8762/eureka

spring:
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      connect-timeout: 10s
      timeout: 5s
      database: 0
